services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - APP_LOGGING_FILE_LOCATION=${APP_LOGGING_FILE_LOCATION}
      - APP_LOGGING_MAX_FILE_SIZE=${APP_LOGGING_MAX_FILE_SIZE}
      - APP_LOGGING_MAX_HISTORY}=${APP_LOGGING_MAX_HISTORY}
      - APP_LOGGING_TOTAL_SIZE_CAP=${APP_LOGGING_TOTAL_SIZE_CAP}
      - APP_FEIGN_NAMES_BIN_LIST_URL=${APP_FEIGN_NAMES_BIN_LIST_URL}
      - APP_FEIGN_NAMES_BIN_LIST_NAME=${APP_FEIGN_NAMES_BIN_LIST_NAME}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT}
      - SPRING_REDIS_LETTUCE_POOL_MAX_ACTIVE=${SPRING_REDIS_LETTUCE_POOL_MAX_ACTIVE}
      - SPRING_REDIS_LETTUCE_POOL_MAX_IDLE=${SPRING_REDIS_LETTUCE_POOL_MAX_IDLE}
      - SPRING_REDIS_LETTUCE_POOL_MIN_IDLE=${SPRING_REDIS_LETTUCE_POOL_MIN_IDLE}
      - SPRING_REDIS_LETTUCE_POOL_MAX_WAIT=${SPRING_REDIS_LETTUCE_POOL_MAX_WAIT}
      - SPRING_REDIS_TIMEOUT=${SPRING_REDIS_TIMEOUT}
      - SPRING_REDIS_LETTUCE_SHUTDOWN_TIMEOUT=${SPRING_REDIS_LETTUCE_SHUTDOWN_TIMEOUT}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_LIQUIBASE_CHANGE_LOG=${SPRING_LIQUIBASE_CHANGE_LOG}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_LIQUIBASE_ENABLED=${SPRING_LIQUIBASE_ENABLED}
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_TOMCAT_THREADS_MAX=${SERVER_TOMCAT_THREADS_MAX}
      - SERVER_TOMCAT_THREADS_MIN_SPARE=${SERVER_TOMCAT_THREADS_MIN_SPARE}
      - SERVER_TOMCAT_CONNECTION_TIMEOUT=${SERVER_TOMCAT_CONNECTION_TIMEOUT}
      - SERVER_TOMCAT_KEEP_ALIVE_TIMEOUT=${SERVER_TOMCAT_KEEP_ALIVE_TIMEOUT}
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-data-prod:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data-prod: